Algoritmo "Exercicio22"

var numHoras: inteiro
   salarioHora,salarioTotal,horaExtra:real

Inicio

   escreva("Digite o numero de horas trabalhadas:")
   leia(numHoras)
   escreva("Digite o salario por horas:")
   leia(salarioHora)
   se (numHoras > 160) entao
 horaExtra:= ( numHoras -160)* (salariohora*0,5)
      fimse
      salarioTotal:=(numHoras* salarioHora + horaExtra)

   escreval ("Salario Total:", salarioTotal)



Fimalgoritmo