Algoritmo "EXERCICIO75"
//Escreva um algoritmo que imprima a tabuada (de 1 a 10) para os números de 1 a 10.

var Numero, cont, resul: inteiro
inicio
   Cont<- 1
   escreva ("escreva o numero: ")
   Leia(Numero)
   Enquanto Cont <=10 faca
      resul<- (Numero * Cont)
      Escreva(Numero)
      Escreva( " X " )
      Escreva(Cont)
      Escreva(" =")
      Escreval(resul)
      Cont<- Cont + 1
   fimenquanto
fimalgoritmo















