Algoritmo "Exercicio 6"

// Data atual  : 11/03/2023
Var
base,altura,area,perimetro: real

Inicio
Escreval("Digite o valor da base:")
leia(base)
Escreval("Digite o valor da altura:")
leia(altura)
Escreval("Digite o terceiro lado:")
Escreval // pular linha

  area <- base* altura
  perimetro <- (2*base) + (2*altura)
  
  Escreval("A area do retangulo e: ", area)
  Escreval  // pular linha
   Escreval("O perimetro do retangulo e: ", perimetro)
Fimalgoritmo